talent_gateway/talent_gateway/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from talent_portal import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', views.JobListView.as_view(), name="job_listing"),
    url(r'^job/(?P<job_id>\d+)$', views.job_detail, name='job_detail'),
    url(r'^job/apply$', views.job_apply, name='job_apply'),
    url(r'^home/$', views.homepage, name="home"),
    url(r'^dataentry/$', views.data_entry_page, name="data-entry"),
    url(r'^dataentry/userlist/data/$', views.OrderListJson.as_view(), name="userList"),
    url(r'^dataentry/userlist/$', views.user_list_page, name="userListPage"),
    url(r'^dataentry/filter/create$', views.save_filter, name="saveFilter"),
    url(r'^dataentry/filter/$', views.get_filters, name="filter_list"),
    url(r'^dataentry/upload/$', views.updload_records, name="updload_records"),
    url(r'^task/status/(?P<task_id>[\w\-]+)/$', views.get_task_status, name="task_status"),
    url(r'^user/$', views.user_view, name="user-view"),
    url(r'^user/edit/(?P<id>[\w\-]+)/$', views.edit_record, name="edit-user"),
    url(r'^user/save/$', views.save_record, name="save-user"),
    url(r'^unauthorized/', views.unauthorized, name="unauthorized"),
    url(r'^download/(?P<path>.*)$', views.download, name="download-rar")
]

talent_gateway/talent_portal/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField

states_and_uts = ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam',
                  'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu',
                  'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir',
                  'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh',
                  'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
                  'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
                  'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Not Available']
STATE_CHOICES = map(lambda x: (x, x), states_and_uts)


# Create your models here.
class Customer(AbstractUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('-', 'Not Available'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='-')
    secondary_email = models.EmailField(max_length=70, blank=True, null=True)
    dob = models.DateField(default=datetime.now, blank=True, null=True)
    mobile = models.CharField(max_length=256, blank=True, null=True)
    secondary_mobile = models.CharField(max_length=256, blank=True, null=True)

    ug_degree = models.CharField(max_length=256, blank=True, null=True)
    ug_completion_year = models.IntegerField(null=True, blank=True)
    ug_college = models.CharField(max_length=256, blank=True, null=True)
    ug_course = models.CharField(max_length=256, blank=True, null=True)

    pg_degree = models.CharField(max_length=256, blank=True, null=True)
    pg_completion_year = models.IntegerField(null=True, blank=True)
    pg_college = models.CharField(max_length=256, blank=True, null=True)
    pg_course = models.CharField(max_length=256, blank=True, null=True)

    additional_degree = models.CharField(max_length=256, blank=True, null=True)
    additional_completion_year = models.IntegerField(null=True, blank=True)
    additional_college = models.CharField(max_length=256, blank=True, null=True)
    additional_course = models.CharField(max_length=256, blank=True, null=True)

    total_experience = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=19)

    current_company = models.CharField(max_length=256, blank=True, null=True)
    current_location = models.CharField(max_length=256, blank=True, null=True,
                                        choices=STATE_CHOICES)
    current_salary = models.IntegerField(null=True, blank=True)
    current_designation = models.CharField(max_length=256, blank=True, null=True)
    current_exprience = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=19)

    industry = models.CharField(max_length=256, blank=True, null=True)

    primary_skills = models.CharField(max_length=256, blank=True, null=True)
    secondary_skills = models.CharField(max_length=256, blank=True, null=True)

    current_functional_area = models.CharField(max_length=256, blank=True, null=True)
    notice_period = models.IntegerField(null=True, blank=True)

    preferred_location = models.CharField(max_length=256, blank=True, null=True,
                                          choices=STATE_CHOICES)
    preferred_salary = models.IntegerField(null=True, blank=True)
    preferred_functional_area = models.CharField(max_length=256, blank=True, null=True)
    preferred_industry = models.CharField(max_length=256, blank=True, null=True)

    resume_url = models.TextField(null=True, blank=True)
    resume_text = models.TextField(null=True, blank=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object

    batch_id = models.TextField(null=True, blank=True)

    applied_to = models.TextField(null=True, blank=True)
    source = models.TextField(null=True, blank=True)
    application_date = models.TextField(null=True, blank=True)
    category = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.email


class Tag(models.Model):
    user = models.ManyToManyField(Customer)
    name = models.CharField(max_length=256, blank=False, null=False)
    value = models.CharField(max_length=256, blank=False, null=False)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class College(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Degree(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Industry(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class FunctionalArea(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    alias = models.CharField(max_length=256, blank=True, null=True)

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Filter(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    data = JSONField()

    user = models.ManyToManyField(Customer, blank=True)

    TYPE_CHOICES = (
        ('Global', 'Global'),
        ('Local', 'Local'),
    )
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default="Local")

    created_by = models.EmailField(max_length=70, blank=True, null=True)  # who created the object
    created_at = models.DateTimeField(
            auto_now_add=True)  # This should add the created date on its own only once.
    updated_at = models.DateTimeField(
            auto_now=True)  # This should add the updated date every time.

    def __str__(self):
        return self.name


class Job(models.Model):
    job_id = models.CharField(max_length=10, blank=True, null=True)
    posted_by = models.CharField(max_length=256, blank=True, null=True)
    title = models.CharField(max_length=256, blank=True, null=True)

talent_gateway/talent_portal/forms.py
import django.forms as forms
from django.forms import ModelForm
from models import *


class UserForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ['password', 'last_login', 'is_superuser', 'groups', 'user_permissions',
                   'is_active', 'is_staff', 'username', 'date_joined', 'resume_url', 'created_by']

    id = forms.HiddenInput()

    email = forms.Field(disabled=True)

    ug_degree = forms.ModelChoiceField(queryset=Degree.objects.all(), to_field_name="name",
                                       empty_label="Not Available", required=False)
    pg_degree = forms.ModelChoiceField(queryset=Degree.objects.all(), to_field_name="name",
                                       empty_label="Not Available", required=False)
    additional_degree = forms.ModelChoiceField(queryset=Degree.objects.all(), to_field_name="name",
                                               empty_label="Not Available", required=False)

    ug_college = forms.ModelChoiceField(queryset=College.objects.all(), to_field_name="name",
                                        empty_label="Not Available", required=False)
    pg_college = forms.ModelChoiceField(queryset=College.objects.all(), to_field_name="name",
                                        empty_label="Not Available", required=False)
    additional_college = forms.ModelChoiceField(queryset=College.objects.all(),
                                                to_field_name="name", empty_label="Not Available",
                                                required=False)

    ug_course = forms.ModelChoiceField(queryset=Course.objects.all(), to_field_name="name",
                                       empty_label="Not Available", required=False)
    pg_course = forms.ModelChoiceField(queryset=Course.objects.all(), to_field_name="name",
                                       empty_label="Not Available", required=False)
    additional_course = forms.ModelChoiceField(queryset=Course.objects.all(), to_field_name="name",
                                               empty_label="Not Available", required=False)

    current_company = forms.ModelChoiceField(queryset=Company.objects.all(), to_field_name="name",
                                             empty_label="Not Available", required=False)

    industry = forms.ModelChoiceField(queryset=Industry.objects.all(), to_field_name="name",
                                      empty_label="Not Available", required=False)
    preferred_industry = forms.ModelChoiceField(queryset=Industry.objects.all(),
                                                to_field_name="name", empty_label="Not Available",
                                                required=False)

    primary_skills = forms.ModelMultipleChoiceField(queryset=Skill.objects.all(),
                                                    to_field_name="name", required=False)
    secondary_skills = forms.ModelMultipleChoiceField(queryset=Skill.objects.all(),
                                                      to_field_name="name", required=False)

    current_functional_area = forms.ModelChoiceField(queryset=FunctionalArea.objects.all(),
                                                     to_field_name="name",
                                                     empty_label="Not Available", required=False)
    preferred_functional_area = forms.ModelChoiceField(queryset=FunctionalArea.objects.all(),
                                                       to_field_name="name",
                                                       empty_label="Not Available", required=False)

    def clean_primary_skills(self):
        primary_skills = []
        for skill in self.cleaned_data['primary_skills']:
            primary_skills.append(str(skill))
        return ",".join(primary_skills)

    def clean_secondary_skills(self):
        secondary_skills = []
        for skill in self.cleaned_data['secondary_skills']:
            secondary_skills.append(str(skill))
        return ",".join(secondary_skills)


class JobApplicantForm(ModelForm):
    class Meta:
        model = JobApplicant
        exclude = ['job', 'resume_url']

talent_gateway/talent_portal/templates/_filter_list.html
{% load custom_template_filters %}
<div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Filters ({{ count }})</h3>
                            </div>
                            {% if count == 0 %}

                                <div class="panel-body">
                                    <p>No saved filters found!</p>
                                </div>

                            {% else %}

                                <ul class="list-group">
                                    {% for global_filter in global_filters %}
                                        <li class="list-group-item filter_a">
                                            <a href="#"
                                               data-filter="{{ global_filter.data|jsonify }}">
                                                {{ global_filter.name }}</a>
                                        </li>
                                    {% endfor %}
                                    {% for local_filter in local_filters %}
                                        <li class="list-group-item filter_a">
                                            <a href="#"
                                               data-filter="{{ local_filter.data|jsonify }}">
                                                {{ local_filter.name }}</a>
                                        </li>
                                    {% endfor %}
                                    </li>
                                </ul>

                            {% endif %}


                        </div>

talent_gateway/talent_portal/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
<html>
<head>
    <!-- for favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <title>{% block head_title %}{% endblock %}</title>

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <script type="text/javascript">
        $.fn.bsmodal = $.fn.modal;
    </script>

    <link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <link type="text/css" href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">


    <script type="text/javascript" src="{% static 'js/chosen.jquery.min.js' %}"></script>
    <link type="text/css" href="{% static 'css/chosen.min.css' %}" rel="stylesheet">

    <link type="text/css" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <script>
        /*** Handle jQuery plugin naming conflict between jQuery UI and Bootstrap ***/
        $.widget.bridge('uibutton', $.ui.button);
        $.widget.bridge('uitooltip', $.ui.tooltip);
    </script>

    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extra_head %}
    {% endblock %}
</head>

<body class="body_content">
{% for message in messages %}

    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
    </div>
{% endfor %}


<div id="loader_overlay" class="overlay">
    <div class="progress center-progress-bar">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            <div class="progress-message">Uploading...</div>
        </div>
    </div>
</div>

{% block body %}

{% endblock %}
{% block content %}

{% endblock %}

</body>


{% block script %}
{% endblock %}

</html>

talent_gateway/talent_portal/templates/customer_base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
<html>
<head>
    <!-- for favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <title>{% block head_title %}{% endblock %}</title>

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <script type="text/javascript">
        $.fn.bsmodal = $.fn.modal;
    </script>

    <link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <link type="text/css" href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">


    <script type="text/javascript" src="{% static 'js/chosen.jquery.min.js' %}"></script>
    <link type="text/css" href="{% static 'css/chosen.min.css' %}" rel="stylesheet">

    <link type="text/css" href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <script>
        /*** Handle jQuery plugin naming conflict between jQuery UI and Bootstrap ***/
        $.widget.bridge('uibutton', $.ui.button);
        $.widget.bridge('uitooltip', $.ui.tooltip);
    </script>

    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>

    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extra_head %}
    {% endblock %}
</head>

<body class="body_content">
{% for message in messages %}

    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
    </div>
{% endfor %}


<div id="loader_overlay" class="overlay">
    <div class="progress center-progress-bar">
        <div class="progress-bar progress-bar-striped active" role="progressbar"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
            <div class="progress-message">Uploading...</div>
        </div>
    </div>
</div>

{% block body %}

{% endblock %}
{% block content %}

{% endblock %}

</body>


{% block script %}
{% endblock %}

</html>

talent_gateway/talent_portal/templates/edit_customer.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load staticfiles %}

{% block body %}

    <div class="container">
        <h1>User - {{ user.email }}</h1>
        <div class="row">
            <div class="col-lg-4 pull-right">

                {% if url %}
                    <button id="download-button" type="button" class="btn btn-warning" target='_blank' data-url="{{ url }}">Download
                        Resume
                    </button>
                {% else %}
                    <button class="btn btn-success disabled" type="button" title="Resume not available">Download Resume
                    </button>
                {% endif %}
                <button id="upload-resume-button" type="button" class="btn btn-info">Upload Resume
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7">

                <form class="form-horizontal" role="form" id="saveForm" method="post"
                      action="{% url 'save-user' %}" novalidate>
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="download_url" value="{{ url }}">
                    {% csrf_token %}
                    {{ form|bootstrap_horizontal:'col-lg-4' }}

                    <div class="btn-block">
                        <div class="col-lg-4"></div>
                        <div class="col-lg-8">
                            <input type="submit" type="button" class="btn btn-success" value="Save">
                            <input type="button" id="cancel_button" class="btn btn-danger" data-url="{% url 'userListPage' %}" value="Cancel">
                        </div>

                    </div>
                </form>


            </div>


        </div>

    </div>




{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {

            $("#download-button").on("click", function () {
                window.open($(this).data("url"), '_blank');
            });

            $("#cancel_button").on("click", function () {
                window.location = $(this).data("url");
            });

            $("#id_dob").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "yy-mm-dd"
            });

            var select = $("select");

            select.chosen({no_results_text: 'Press Enter to add new entry:'});

            select.each(function (index, item) {

                item = $(item);
                var chosen = item.data('chosen');

                if (chosen.dropdown.find('input').length == 0) {
                    // for multi-select
                    chosen.dropdown.siblings('.chosen-choices').find('input').on('keyup', function (e) {
                        // if we hit Enter and the results list is empty (no matches) add the option
                        if (e.which == 13 && chosen.dropdown.find('li.no-results').length > 0) {
                            var option = $("<option>").val(this.value).text(this.value);

                            // add the new option
                            item.prepend(option);
                            // automatically select it
                            item.find(option).prop('selected', true);
                            // trigger the update
                            item.trigger("chosen:updated");
                        }
                    });
                }
                else {
                    chosen.dropdown.find('input').on('keyup', function (e) {
                        // if we hit Enter and the results list is empty (no matches) add the option
                        if (e.which == 13 && chosen.dropdown.find('li.no-results').length > 0) {
                            var option = $("<option>").val(this.value).text(this.value);

                            // add the new option
                            item.prepend(option);
                            // automatically select it
                            item.find(option).prop('selected', true);
                            // trigger the update
                            item.trigger("chosen:updated");
                        }
                    });
                }


            });


        });
    </script>
{% endblock %}

talent_gateway/talent_portal/templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block body %}

<h1>Welcome to dashboard</h1>

    <h3>
    work in progress!
    </h3>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {

    });
</script>
{% endblock %}

talent_gateway/talent_portal/templates/job_listing.html
{% extends 'customer_base.html' %}
{% load i18n %}

{% block body %}

    <div class="container">
        <h1>Available Jobs</h1>

        {% if job_list %}


            <table class="table table-hover table-bordered table-striped">
                <thead>
                <tr>
                    <th>Job Id</th>
                    <th>Title</th>
                    <th>Posted by</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>


                {% for job in job_list %}
                    <tr>
                        <th scope="row">{{ job.job_id }}</th>
                        <td>{{ job.title }}</td>
                        <td>{{ job.posted_by }}</td>

                        <td><a href="{% url 'job_detail' job.id %}">Details/Apply</a></td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>





            {% if is_paginated %}
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    <span>Previous</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#">
                                    <span>Previous</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page in paginator.page_range %}
                            <li {% if page == page_obj.number %}class="active"{% endif %}>
                                <a href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}">
                                    <span>Next</span>
                                </a>
                            </li>
                        {% else %}
                            <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
                                <a href="#">
                                    <span>Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}



        {% else %}
            <p>There are no jobs available at the moment.</p>
        {% endif %}

    </div>





{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {

        });
    </script>
{% endblock %}